### ISSUE TITLE
Attributeerror

### ISSUE THREAD

**Issue by FeelsBadMan1** [Derfirm/pornhub-api#130]
Hello, seems like the libary do not have api.stats.all() and api.stats.all_detailed() however this is included in the read.me
I wanted t print out the stats so i used following code:
```py
print(api.stats.all_detailed())
```
After running the code i got this issue:
```py
Traceback (most recent call last):
  File "D:\my_python_projects\pornhub_discordbot\bot.py", line 20, in <module>
    print(api.stats.all_detailed())
AttributeError: 'PornhubApi' object has no attribute 'stats'
```
The same Traceback happen when using print(api.stats.all())
Hopefully you could help me there

**Comment by Derfirm** [comment]
Hello :)
Thanks for important notice!
unfortunately I made a typo in readme, it must be `api.stars...`

**Comment by FeelsBadMan1** [comment]
well that worked. thx
