### ISSUE TITLE
is it possible to get a stream of all new videos?

### ISSUE THREAD

**Issue by Mr-Steal-Your-Script** [Derfirm/pornhub-api#43]

**Comment by Derfirm** [comment]
hey @Mr-Steal-Your-Script 
Tthanks for the question.
It should be noted right away that the current api is based on rest-api and provides only a more convenient and typed response. As for the stream, this can potentially be done by implementing your own backend and taking data in "chunks". If we are talking about polling or opening a long connection, then I would like to hear the problem in a little more detail.

**Comment by Mr-Steal-Your-Script** [comment]
Thanks for the quick response! I was trying to get a stream of all videos with a certain keyword, so that I could add it together with PRAW and automatically submit to a subreddit.

**Comment by Derfirm** [comment]
ok, I think I get the idea.
In an amicable way, it is worth creating a kind of wrapper and periodically calling the api with the necessary parameters, iterating through the pages along the way (if necessary).
in pseudocode it might look like
```
def stream(timeout, **params):
    while True:
        result = api.get_videos(**params)
        for video in result.videos:
           yield video
        sleep(timeout)
```
@Mr-Steal-Your-Script  did I understand You correctly?

**Comment by Mr-Steal-Your-Script** [comment]
yes, this is working. thanks.
